export const TOOL_LABELS: Record<string, string> = {
  create_blog: "Creating blog post",
  create_calendar_event: "Creating calendar event",
  create_group: "Creating group",
  create_kanban_board: "Creating kanban board",
  create_kanban_card: "Creating kanban card",
  create_kanban_column: "Creating kanban column",
  create_note: "Creating note",
  create_paper: "Creating paper",
  create_person: "Adding person",
  create_person_group: "Creating people group",
  create_resource: "Creating resource",
  create_timetable_entry: "Creating timetable entry",
  delete_blog: "Deleting blog post",
  delete_calendar_event: "Deleting calendar event",
  delete_course: "Deleting course",
  delete_course_deadline: "Deleting course deadline",
  delete_email: "Deleting email",
  delete_group: "Deleting group",
  delete_kanban_board: "Deleting kanban board",
  delete_kanban_card: "Deleting kanban card",
  delete_kanban_column: "Deleting kanban column",
  delete_note: "Deleting note",
  delete_paper: "Deleting paper",
  delete_person: "Deleting person",
  delete_person_group: "Deleting people group",
  delete_resource: "Deleting resource",
  delete_timetable_entry: "Deleting timetable entry",
  generate_email_draft: "Drafting email",
  get_blog: "Read blog post",
  get_calendar_events: "Fetched calendar events",
  get_contact: "Read contact",
  get_email: "Read email",
  get_github_repository_context: "Inspected GitHub repository",
  get_healthy_resources: "Fetched healthy resources",
  get_kanban_board: "Fetched kanban board",
  get_note: "Read note",
  get_paper: "Read paper",
  get_now_page: "Fetched now page",
  get_person: "Read person",
  get_project: "Read project",
  get_resource_by_id: "Fetched resource",
  get_resource_health: "Checked resource health",
  get_resources: "Fetched resources",
  get_timetable: "Fetched timetable",
  import_sandbox_spreadsheet: "Importing spreadsheet",
  list_account_emails: "Listed account emails",
  list_blogs: "Listed blog posts",
  list_contacts: "Listed contacts",
  list_email_accounts: "Listed email accounts",
  list_emails: "Listed emails",
  list_groups: "Listed groups",
  list_kanban_boards: "Listed kanban boards",
  list_kanban_cards: "Listed kanban cards",
  list_kanban_columns: "Listed kanban columns",
  list_notes: "Listed notes",
  list_papers: "Listed papers",
  list_people: "Listed people",
  list_person_groups: "Listed people groups",
  list_projects: "Listed projects",
  list_timeline_items: "Fetched timeline",
  mark_email_as_read: "Marking email as read",
  query_emails: "Searched emails",
  reboot_resource: "Rebooting resource",
  reorder_kanban_cards: "Reordering kanban cards",
  reply_to_contact: "Replying to contact",
  request_send_email: "Requesting email send",
  resolve_course: "Resolved course",
  restart_resource_service: "Restarting service",
  save_project_draft: "Saving project draft",
  search_blogs: "Searched blogs",
  search_notes: "Searched notes",
  resolve_paper_metadata: "Resolved paper metadata",
  add_paper_highlight: "Adding paper highlight",
  link_note_to_paper: "Linking note to paper",
  semantic_classify_note: "Classifying note",
  set_person_relations: "Updating relations",
  update_blog: "Updating blog post",
  update_calendar_event: "Updating calendar event",
  update_contact_status: "Updating contact status",
  update_course_deadline: "Updating course deadline",
  update_group: "Updating group",
  update_kanban_board: "Updating kanban board",
  update_kanban_card: "Updating kanban card",
  update_kanban_column: "Updating kanban column",
  update_note: "Updating note",
  update_paper: "Updating paper",
  update_now_page: "Updating now page",
  update_person: "Updating person",
  update_person_group: "Updating people group",
  update_resource: "Updating resource",
  update_timetable_entry: "Updating timetable entry",
  upload_sandbox_file: "Uploading generated file",
  web_search: "Searched the web",

  search_symbols: "Searched symbols",
  get_symbol: "Read symbol",
  get_quotes: "Fetched quotes",
  get_price_history: "Fetched price history",
  get_technicals: "Computed technicals",
  get_symbol_news: "Fetched market news",
  get_fundamentals: "Fetched fundamentals",
  get_filings: "Fetched SEC filings",
  get_corporate_actions: "Fetched corporate actions",
  get_markets_budget: "Checked provider budget",
  list_portfolios: "Listed portfolios",
  get_portfolio: "Read portfolio",
  get_portfolio_curve: "Fetched equity curve",
  create_portfolio: "Creating portfolio",
  update_portfolio: "Updating portfolio",
  delete_portfolio: "Deleting portfolio",
  list_trades: "Listed trades",
  add_trade: "Recording trade",
  delete_trade: "Deleting trade",
  sync_portfolio_actions: "Syncing corporate actions",
  list_watchlists: "Listed watchlists",
  create_watchlist: "Creating watchlist",
  update_watchlist: "Updating watchlist",
  delete_watchlist: "Deleting watchlist",
};

export function getToolLabel(toolName: string) {
  return TOOL_LABELS[toolName] ?? humanizeToolName(toolName);
}

function humanizeToolName(toolName: string) {
  const words = toolName
    .replace(/_/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();

  if (!words) return "Using tool";
  return words.charAt(0).toUpperCase() + words.slice(1);
}
