export const TOOL_LABELS: Record<string, string> = {
  accept_latex_reference: "Accepting LaTeX reference",
  accept_semantic_suggestion: "Accepting semantic suggestion",
  accept_triage_suggestion: "Accepting triage suggestion",
  add_course_assignment: "Adding course assignment",
  add_course_deadline: "Adding course deadline",
  add_paper_highlight: "Adding paper highlight",
  add_today_board_elements: "Adding today board elements",
  add_trade: "Recording trade",
  add_whiteboard_elements: "Adding whiteboard elements",
  amend_order: "Amending order",
  approve_blog_comment: "Approving comment",
  archive_course: "Archiving course",
  archive_triage_category: "Archiving triage category",
  attach_voice_note_to_note: "Attaching voice note",
  cancel_agent_task: "Cancelling agent task",
  cancel_order: "Cancelling order",
  compile_cv: "Compiling CV",
  compile_latex_project: "Compiling LaTeX project",
  complete_course_deadline: "Completing course deadline",
  contribute_to_finance_envelope: "Recording contribution",
  create_agent_goal: "Creating agent goal",
  create_agent_procedure: "Creating agent procedure",
  create_authenticator_account: "Creating authenticator account",
  create_blog: "Creating blog post",
  create_calendar_event: "Creating calendar event",
  create_conversation: "Creating conversation",
  create_course: "Creating course",
  create_expected_finance_entry: "Creating expected finance entry",
  create_finance_category: "Creating finance category",
  create_finance_entry: "Creating finance entry",
  create_finance_entry_from_text: "Recording transaction",
  create_finance_envelope: "Creating budget envelope",
  create_finance_rule: "Creating finance rule",
  create_group: "Creating group",
  create_journal_entry: "Creating journal entry",
  create_kanban_board: "Creating kanban board",
  create_kanban_card: "Creating kanban card",
  create_kanban_column: "Creating kanban column",
  create_latex_project: "Creating LaTeX project",
  create_note: "Creating note",
  create_note_from_voice: "Creating note from voice note",
  create_paper: "Creating paper",
  create_person: "Adding person",
  create_person_group: "Creating people group",
  create_picron_job: "Creating PiCron job",
  create_portfolio: "Creating portfolio",
  create_project: "Creating project",
  create_resource: "Creating resource",
  create_sub_resource: "Creating sub resource",
  create_timeline_item: "Creating timeline item",
  create_timetable_entry: "Creating timetable entry",
  create_watchlist: "Creating watchlist",
  create_whiteboard: "Creating whiteboard",
  delete_authenticator_account: "Deleting authenticator account",
  delete_blog: "Deleting blog post",
  delete_blog_comment: "Deleting comment",
  delete_calendar_event: "Deleting calendar event",
  delete_contact: "Deleting contact",
  delete_conversation: "Deleting conversation",
  delete_course: "Deleting course",
  delete_course_assignment: "Deleting course assignment",
  delete_course_deadline: "Deleting course deadline",
  delete_email: "Deleting email",
  delete_finance_category: "Deleting finance category",
  delete_finance_entry: "Deleting finance entry",
  delete_finance_envelope: "Deleting budget envelope",
  delete_finance_rule: "Deleting finance rule",
  delete_group: "Deleting group",
  delete_journal_entry: "Deleting journal entry",
  delete_kanban_board: "Deleting kanban board",
  delete_kanban_card: "Deleting kanban card",
  delete_kanban_column: "Deleting kanban column",
  delete_latex_file: "Deleting LaTeX file",
  delete_latex_project: "Deleting LaTeX project",
  delete_note: "Deleting note",
  delete_paper: "Deleting paper",
  delete_person: "Deleting person",
  delete_person_group: "Deleting people group",
  delete_picron_job: "Deleting PiCron job",
  delete_portfolio: "Deleting portfolio",
  delete_project: "Deleting project",
  delete_resource: "Deleting resource",
  delete_spreadsheet: "Deleting spreadsheet",
  delete_sub_resource: "Deleting sub resource",
  delete_timeline_item: "Deleting timeline item",
  delete_timetable_entry: "Deleting timetable entry",
  delete_today_board_elements: "Deleting today board elements",
  delete_trade: "Deleting trade",
  delete_voice_note: "Deleting voice note",
  delete_watchlist: "Deleting watchlist",
  delete_whiteboard_elements: "Deleting whiteboard elements",
  disconnect_finance_account: "Disconnecting finance account",
  dismiss_semantic_suggestion: "Dismissing semantic suggestion",
  dismiss_triage_suggestion: "Dismissing triage suggestion",
  draft_finance_envelopes: "Drafting budget from history",
  duplicate_latex_project: "Duplicating LaTeX project",
  evaluate_finance_budget_alerts: "Evaluating budget alerts",
  find_course_emails: "Found course emails",
  generate_email_draft: "Drafting email",
  generate_finance_budget_suggestions: "Reviewing the budget",
  get_app_settings: "Fetched app settings",
  get_authenticator_codes: "Fetched authenticator codes",
  get_blog: "Read blog post",
  get_calendar_events: "Fetched calendar events",
  get_contact: "Read contact",
  get_conversation: "Fetched conversation",
  get_corporate_actions: "Fetched corporate actions",
  get_course: "Fetched course",
  get_current_page_context: "Read page context",
  get_cv: "Fetched CV",
  get_email: "Read email",
  get_filings: "Fetched SEC filings",
  get_finance_budget: "Fetched budget",
  get_finance_entry: "Fetched finance entry",
  get_finance_narrative: "Fetched finance narrative",
  get_finance_overview: "Fetched finance overview",
  get_finance_settings: "Fetched finance settings",
  get_fundamentals: "Fetched fundamentals",
  get_github_repository_context: "Inspected GitHub repository",
  get_healthy_resources: "Fetched healthy resources",
  get_journal_entry: "Fetched journal entry",
  get_kanban_board: "Fetched kanban board",
  get_latex_project: "Fetched LaTeX project",
  get_markets_budget: "Checked provider budget",
  get_note: "Read note",
  get_now_page: "Fetched now page",
  get_paper: "Read paper",
  get_person: "Read person",
  get_personal_user_model: "Fetched user model",
  get_picron_job: "Fetched PiCron job",
  get_picron_job_history: "Fetched PiCron job history",
  get_picron_stats: "Fetched PiCron stats",
  get_portfolio: "Read portfolio",
  get_portfolio_curve: "Fetched equity curve",
  get_price_history: "Fetched price history",
  get_project: "Read project",
  get_quotes: "Fetched quotes",
  get_resource_by_id: "Fetched resource",
  get_resource_health: "Checked resource health",
  get_resources: "Fetched resources",
  get_semester_overview: "Fetched semester overview",
  get_symbol: "Read symbol",
  get_symbol_news: "Fetched market news",
  get_technicals: "Computed technicals",
  get_timetable: "Fetched timetable",
  get_today_board: "Fetched today board",
  get_triage_settings: "Fetched triage settings",
  get_voice_note: "Fetched voice note",
  get_whiteboard: "Fetched whiteboard",
  import_finance_csv: "Importing CSV",
  import_sandbox_spreadsheet: "Importing spreadsheet",
  link_finance_entries: "Linking finance entries",
  link_kanban_card: "Linking kanban card",
  link_note_to_paper: "Linking note to paper",
  link_notes: "Linking notes",
  link_to_course: "Linking to course",
  list_account_emails: "Listed account emails",
  list_agent_goals: "Listed agent goals",
  list_agent_procedures: "Listed agent procedures",
  list_agent_tasks: "Listed agent tasks",
  list_authenticator_accounts: "Listed authenticator accounts",
  list_blog_comments: "Listed comments",
  list_blogs: "Listed blog posts",
  list_contacts: "Listed contacts",
  list_conversations: "Listed conversations",
  list_courses: "Listed courses",
  list_email_accounts: "Listed email accounts",
  list_emails: "Listed emails",
  list_finance_accounts: "Listed finance accounts",
  list_finance_budget_alerts: "Listed budget alerts",
  list_finance_budget_suggestions: "Listed budget suggestions",
  list_finance_categories: "Listed finance categories",
  list_finance_entries: "Listed finance entries",
  list_finance_envelopes: "Listed budget envelopes",
  list_finance_match_reviews: "Listed finance match reviews",
  list_finance_rules: "Listed finance rules",
  list_groups: "Listed groups",
  list_journal_entries: "Listed journal entries",
  list_kanban_boards: "Listed kanban boards",
  list_kanban_cards: "Listed kanban cards",
  list_kanban_columns: "Listed kanban columns",
  list_latex_history: "Listed LaTeX history",
  list_latex_projects: "Listed LaTeX projects",
  list_llm_models: "Listed LLM models",
  list_note_edges: "Listed note edges",
  list_note_tags: "Listed note tags",
  list_notes: "Listed notes",
  list_orders: "Listed orders",
  list_papers: "Listed papers",
  list_people: "Listed people",
  list_person_groups: "Listed people groups",
  list_picron_jobs: "Listed PiCron jobs",
  list_portfolios: "Listed portfolios",
  list_projects: "Listed projects",
  list_resource_capabilities: "Listed resource capabilities",
  list_resource_services: "Listed resource services",
  list_semantic_runs: "Listed semantic runs",
  list_semantic_suggestions: "Listed semantic suggestions",
  list_spreadsheets: "Listed spreadsheets",
  list_sub_resources: "Listed sub resources",
  list_timeline_items: "Fetched timeline",
  list_trades: "Listed trades",
  list_triage: "Listed triage",
  list_voice_notes: "Listed voice notes",
  list_watchlists: "Listed watchlists",
  list_whiteboards: "Listed whiteboards",
  mark_email_as_read: "Marking email as read",
  navigate_desktop: "Navigating",
  place_order: "Placing order",
  project_course_grade: "Projected course grade",
  publish_cv: "Publishing CV",
  query_emails: "Searched emails",
  read_latex_file: "Read LaTeX file",
  read_spreadsheet: "Read spreadsheet",
  reboot_resource: "Rebooting resource",
  refresh_current_page: "Refreshing page",
  refresh_finance_fx: "Refreshing FX rates",
  reject_blog_comment: "Rejecting comment",
  remove_finance_envelope_contribution: "Removing contribution",
  rename_spreadsheet: "Renaming spreadsheet",
  rename_voice_note: "Renaming voice note",
  reorder_kanban_cards: "Reordering kanban cards",
  reorder_projects: "Reordering projects",
  reply_to_contact: "Replying to contact",
  request_send_email: "Requesting email send",
  resolve_course: "Resolved course",
  resolve_finance_budget_alert: "Resolving budget alert",
  resolve_finance_budget_suggestion: "Applying budget suggestion",
  resolve_finance_match_review: "Resolving finance match review",
  resolve_paper_metadata: "Resolved paper metadata",
  restart_resource_service: "Restarting service",
  restore_latex_revision: "Restoring LaTeX revision",
  retire_agent_procedure: "Retiring agent procedure",
  run_resource_health_checks: "Running health checks",
  run_semantic_sync: "Running semantic sync",
  run_triage: "Running triage",
  sandbox_list_files: "Listed sandbox files",
  sandbox_port_url: "Fetched sandbox port URL",
  sandbox_read_file: "Read sandbox file",
  sandbox_run_command: "Running sandbox command",
  sandbox_stop: "Stopping sandbox",
  sandbox_write_files: "Writing sandbox files",
  save_cv_project: "Saving CV project",
  save_memory: "Saving memory",
  save_project_draft: "Saving project draft",
  schedule_agent_task: "Scheduling agent task",
  search_blogs: "Searched blogs",
  search_latex_data_points: "Searched LaTeX data points",
  search_latex_references: "Searched LaTeX references",
  search_notes: "Searched notes",
  search_symbols: "Searched symbols",
  semantic_classify_note: "Classifying note",
  set_course_triage_context: "Setting course triage context",
  set_finance_fx_rate: "Setting FX rate",
  set_person_relations: "Updating relations",
  set_today_board_background: "Setting today board background",
  set_triage_status: "Setting triage status",
  set_whiteboard_background: "Setting whiteboard background",
  summarize_finance_spend: "Summarised spend",
  sync_email_accounts: "Syncing email",
  sync_finance_account: "Syncing finance account",
  sync_portfolio_actions: "Syncing corporate actions",
  toggle_project_active: "Toggling project active",
  toggle_project_featured: "Toggling project featured",
  toggle_timeline_item_active: "Toggling timeline item active",
  transcribe_voice_note: "Transcribing voice note",
  trigger_picron_job: "Triggering PiCron job",
  unlink_finance_entry: "Unlinking finance entry",
  unlink_from_course: "Unlinking from course",
  unlink_kanban_card: "Unlinking kanban card",
  unlink_notes: "Unlinking notes",
  update_agent_goal: "Updating agent goal",
  update_app_settings: "Updating app settings",
  update_authenticator_account: "Updating authenticator account",
  update_blog: "Updating blog post",
  update_calendar_event: "Updating calendar event",
  update_contact_status: "Updating contact status",
  update_course: "Updating course",
  update_course_assignment: "Updating course assignment",
  update_course_deadline: "Updating course deadline",
  update_finance_account: "Updating finance account",
  update_finance_category: "Updating finance category",
  update_finance_entry: "Updating finance entry",
  update_finance_envelope: "Updating budget envelope",
  update_finance_rule: "Updating finance rule",
  update_finance_settings: "Updating finance settings",
  update_group: "Updating group",
  update_journal_entry: "Updating journal entry",
  update_kanban_board: "Updating kanban board",
  update_kanban_card: "Updating kanban card",
  update_kanban_column: "Updating kanban column",
  update_note: "Updating note",
  update_now_page: "Updating now page",
  update_paper: "Updating paper",
  update_person: "Updating person",
  update_person_group: "Updating people group",
  update_picron_job: "Updating PiCron job",
  update_portfolio: "Updating portfolio",
  update_project: "Updating project",
  update_resource: "Updating resource",
  update_sub_resource: "Updating sub resource",
  update_timeline_item: "Updating timeline item",
  update_timetable_entry: "Updating timetable entry",
  update_today_board_element: "Updating today board element",
  update_triage_settings: "Updating triage settings",
  update_watchlist: "Updating watchlist",
  update_whiteboard_element: "Updating whiteboard element",
  upload_file_from_base64: "Uploading file",
  upload_file_from_url: "Uploading file",
  upload_sandbox_file: "Uploading generated file",
  view_today_board: "Viewed today board",
  view_whiteboard: "Viewed whiteboard",
  write_latex_file: "Writing LaTeX file",
};

export function getToolLabel(toolName: string) {
  return TOOL_LABELS[toolName] ?? humanizeToolName(toolName);
}

function humanizeToolName(toolName: string) {
  const words = toolName
    .replace(/_/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();

  if (!words) return "Using tool";
  return words.charAt(0).toUpperCase() + words.slice(1);
}
