import type { McpServer } from "@modelcontextprotocol/server";
import type { Api } from "../define";
import { registerWebAgentMemory } from "./agent-memory";
import { registerWebAgentTasks } from "./agent-tasks";
import { registerWebAuthenticator } from "./authenticator";
import { registerWebBackgroundAgent } from "./background-agent";
import { registerWebCalendar } from "./calendar";
import { registerWebContent } from "./content";
import { registerWebConversations } from "./conversations";
import { registerWebCourses } from "./courses";
import { registerWebCv } from "./cv";
import { registerWebEmail } from "./email";
import { registerWebFinance } from "./finance";
import { registerWebKanban } from "./kanban";
import { registerWebLatex } from "./latex";
import { registerWebLlm } from "./llm";
import { registerWebMarkets } from "./markets";
import { registerWebMisc } from "./misc";
import { registerWebNotes } from "./notes";
import { registerWebPapers } from "./papers";
import { registerWebPeople } from "./people";
import { registerWebPlanning } from "./planning";
import { registerWebResources } from "./resources";
import { registerWebSemantic } from "./semantic";
import { registerWebSpreadsheets } from "./spreadsheets";
import { registerWebTriage } from "./triage";
import { registerWebVoiceNotes } from "./voice-notes";

export function registerWeb(server: McpServer, api: Api) {
  registerWebMisc(server, api);
  registerWebContent(server, api);
  registerWebPeople(server, api);
  registerWebResources(server, api);
  registerWebKanban(server, api);
  registerWebNotes(server, api);
  registerWebCalendar(server, api);
  registerWebPlanning(server, api);
  registerWebCourses(server, api);
  registerWebPapers(server, api);
  registerWebSpreadsheets(server, api);
  registerWebEmail(server, api);
  registerWebTriage(server, api);
  registerWebConversations(server, api);
  registerWebAgentTasks(server, api);
  registerWebAgentMemory(server, api);
  registerWebBackgroundAgent(server, api);
  registerWebVoiceNotes(server, api);
  registerWebCv(server, api);
  registerWebLatex(server, api);
  registerWebLlm(server, api);
  registerWebMarkets(server, api);
  registerWebFinance(server, api);
  registerWebSemantic(server, api);
  registerWebAuthenticator(server, api);
}
