import { z } from "zod";

export const macrosNutrientKeys = [
  "calories",
  "water",
  "alcohol",
  "caffeine",
  "cholesterol",
  "choline",
  "carbs",
  "fiber",
  "sugar",
  "addedSugar",
  "polyols",
  "starch",
  "sucrose",
  "glucose",
  "fructose",
  "lactose",
  "maltose",
  "fat",
  "monoUnsaturated",
  "polyUnsaturated",
  "omega3",
  "omega3Ala",
  "omega3Dha",
  "omega3Epa",
  "omega3Dpa",
  "omega6",
  "saturated",
  "transFat",
  "protein",
  "cysteine",
  "histidine",
  "isoleucine",
  "leucine",
  "lysine",
  "methionine",
  "phenylalanine",
  "threonine",
  "tryptophan",
  "tyrosine",
  "valine",
  "a",
  "b1",
  "b2",
  "b3",
  "b5",
  "b6",
  "b12",
  "c",
  "d",
  "e",
  "k",
  "folate",
  "folateDfe",
  "retinol",
  "caroteneBeta",
  "caroteneAlpha",
  "cryptoxanthinBeta",
  "lycopene",
  "luteinZeaxanthin",
  "calcium",
  "copper",
  "iron",
  "magnesium",
  "manganese",
  "phosphorus",
  "potassium",
  "selenium",
  "sodium",
  "zinc",
  "ash",
  "theobromine",
] as const;

export const macrosNutrientKeySchema = z.enum(macrosNutrientKeys);

export type MacrosNutrientKey = z.infer<typeof macrosNutrientKeySchema>;
