CREATE EXTENSION IF NOT EXISTS pgcrypto;
--> statement-breakpoint
CREATE TABLE "items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"barcode" text NOT NULL,
	"name" text NOT NULL,
	"brand" text,
	"serving_label" text NOT NULL,
	"calories_per_serving" numeric(12, 3) DEFAULT 0 NOT NULL,
	"protein_per_serving" numeric(12, 3) DEFAULT 0 NOT NULL,
	"carbs_per_serving" numeric(12, 3) DEFAULT 0 NOT NULL,
	"fat_per_serving" numeric(12, 3) DEFAULT 0 NOT NULL,
	"search_vector_english" "tsvector" GENERATED ALWAYS AS (to_tsvector('english', coalesce(name, '') || ' ' || coalesce(brand, ''))) STORED NOT NULL,
	"search_vector_portuguese" "tsvector" GENERATED ALWAYS AS (to_tsvector('portuguese', coalesce(name, '') || ' ' || coalesce(brand, ''))) STORED NOT NULL,
	"search_vector_spanish" "tsvector" GENERATED ALWAYS AS (to_tsvector('spanish', coalesce(name, '') || ' ' || coalesce(brand, ''))) STORED NOT NULL,
	"search_vector_french" "tsvector" GENERATED ALWAYS AS (to_tsvector('french', coalesce(name, '') || ' ' || coalesce(brand, ''))) STORED NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nutrition_data" (
	"item_id" uuid NOT NULL,
	"serving_label" text NOT NULL,
	"serving_qnty" numeric(12, 3) NOT NULL,
	"serving_unit" text NOT NULL,
	"calories" numeric(12, 3) DEFAULT 0 NOT NULL,
	"water" numeric(12, 3) DEFAULT 0 NOT NULL,
	"alcohol" numeric(12, 3) DEFAULT 0 NOT NULL,
	"caffeine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"cholesterol" numeric(12, 3) DEFAULT 0 NOT NULL,
	"choline" numeric(12, 3) DEFAULT 0 NOT NULL,
	"carbs" numeric(12, 3) DEFAULT 0 NOT NULL,
	"fiber" numeric(12, 3) DEFAULT 0 NOT NULL,
	"sugar" numeric(12, 3) DEFAULT 0 NOT NULL,
	"added_sugar" numeric(12, 3) DEFAULT 0 NOT NULL,
	"polyols" numeric(12, 3) DEFAULT 0 NOT NULL,
	"fat" numeric(12, 3) DEFAULT 0 NOT NULL,
	"mono_unsaturated" numeric(12, 3) DEFAULT 0 NOT NULL,
	"poly_unsaturated" numeric(12, 3) DEFAULT 0 NOT NULL,
	"omega_3" numeric(12, 3) DEFAULT 0 NOT NULL,
	"omega_3_ala" numeric(12, 3) DEFAULT 0 NOT NULL,
	"omega_3_dha" numeric(12, 3) DEFAULT 0 NOT NULL,
	"omega_3_epa" numeric(12, 3) DEFAULT 0 NOT NULL,
	"omega_6" numeric(12, 3) DEFAULT 0 NOT NULL,
	"saturated" numeric(12, 3) DEFAULT 0 NOT NULL,
	"trans_fat" numeric(12, 3) DEFAULT 0 NOT NULL,
	"protein" numeric(12, 3) DEFAULT 0 NOT NULL,
	"cysteine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"histidine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"isoleucine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"leucine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"lysine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"methionine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"phenylalanine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"threonine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"tryptophan" numeric(12, 3) DEFAULT 0 NOT NULL,
	"tyrosine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"valine" numeric(12, 3) DEFAULT 0 NOT NULL,
	"a" numeric(12, 3) DEFAULT 0 NOT NULL,
	"b1" numeric(12, 3) DEFAULT 0 NOT NULL,
	"b2" numeric(12, 3) DEFAULT 0 NOT NULL,
	"b3" numeric(12, 3) DEFAULT 0 NOT NULL,
	"b5" numeric(12, 3) DEFAULT 0 NOT NULL,
	"b6" numeric(12, 3) DEFAULT 0 NOT NULL,
	"b12" numeric(12, 3) DEFAULT 0 NOT NULL,
	"c" numeric(12, 3) DEFAULT 0 NOT NULL,
	"d" numeric(12, 3) DEFAULT 0 NOT NULL,
	"e" numeric(12, 3) DEFAULT 0 NOT NULL,
	"k" numeric(12, 3) DEFAULT 0 NOT NULL,
	"folate" numeric(12, 3) DEFAULT 0 NOT NULL,
	"calcium" numeric(12, 3) DEFAULT 0 NOT NULL,
	"copper" numeric(12, 3) DEFAULT 0 NOT NULL,
	"iron" numeric(12, 3) DEFAULT 0 NOT NULL,
	"magnesium" numeric(12, 3) DEFAULT 0 NOT NULL,
	"manganese" numeric(12, 3) DEFAULT 0 NOT NULL,
	"phosphorus" numeric(12, 3) DEFAULT 0 NOT NULL,
	"potassium" numeric(12, 3) DEFAULT 0 NOT NULL,
	"selenium" numeric(12, 3) DEFAULT 0 NOT NULL,
	"sodium" numeric(12, 3) DEFAULT 0 NOT NULL,
	"zinc" numeric(12, 3) DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "nutrition_data_item_id_pk" PRIMARY KEY("item_id")
);
--> statement-breakpoint
ALTER TABLE "nutrition_data" ADD CONSTRAINT "nutrition_data_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "items_barcode_idx" ON "items" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "items_search_vector_english_idx" ON "items" USING gin ("search_vector_english");--> statement-breakpoint
CREATE INDEX "items_search_vector_portuguese_idx" ON "items" USING gin ("search_vector_portuguese");--> statement-breakpoint
CREATE INDEX "items_search_vector_spanish_idx" ON "items" USING gin ("search_vector_spanish");--> statement-breakpoint
CREATE INDEX "items_search_vector_french_idx" ON "items" USING gin ("search_vector_french");
