/**
 * Native chrome (the tab bar, toolbar buttons and their menus) takes images,
 * not React components, so it gets PNGs of the same Lucide icons the rest of
 * the app draws. Renders each at 1x/2x/3x and writes `src/ui/glyphs.ts`.
 *
 *   bun scripts/render-glyphs.ts
 *
 * Rerun after adding a name below or upgrading lucide-react-native.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const iconsDir = join(root, "node_modules/lucide-react-native/dist/esm/icons");
const outDir = join(root, "assets/glyphs");

/** Toolbar buttons and menu items: the size of a bar button's symbol. */
const TOOLBAR = [
  "arrow-up-down",
  "braces",
  "calendar",
  "chart-column",
  "check",
  "circle-check",
  "circle-ellipsis",
  "circle-user",
  "copy",
  "ellipsis",
  "flame",
  "list-plus",
  "list-x",
  "log-out",
  "notebook-pen",
  "pencil",
  "plus",
  "scan-barcode",
  "scan-text",
  "share",
  "shopping-cart",
  "square-pen",
  "table-2",
  "trash",
  "triangle-alert",
  "utensils",
  "x",
] as const;

/** Tab bar items, drawn heavier when selected like the web app's nav. */
const TABS = [
  "layout-template",
  "apple",
  "circle-plus",
  "chart-line",
  "circle-ellipsis",
] as const;

const TOOLBAR_POINTS = 22;
const TAB_POINTS = 26;

type IconNode = [string, Record<string, string | number>][];

function readNode(name: string): IconNode {
  const source = readFileSync(join(iconsDir, `${name}.mjs`), "utf8");
  const start = source.indexOf("[", source.indexOf("node:"));
  let depth = 0;
  let end = start;
  for (; end < source.length; end++) {
    if (source[end] === "[") depth++;
    else if (source[end] === "]" && --depth === 0) break;
  }
  if (start < 0 || depth !== 0) throw new Error(`No icon node in ${name}.mjs`);
  // The node is a plain literal in lucide's own published file.
  return new Function(`return ${source.slice(start, end + 1)}`)() as IconNode;
}

function toSvg(node: IconNode, strokeWidth: number): string {
  const children = node
    .map(([tag, attributes]) => {
      const attrs = Object.entries(attributes)
        .filter(([key]) => key !== "key")
        .map(([key, value]) => `${key}="${value}"`)
        .join(" ");
      return `<${tag} ${attrs}/>`;
    })
    .join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round">${children}</svg>`;
}

function render(file: string, svg: string, points: number) {
  for (const scale of [1, 2, 3]) {
    const png = new Resvg(svg, {
      fitTo: { mode: "width", value: points * scale },
    })
      .render()
      .asPng();
    const suffix = scale === 1 ? "" : `@${scale}x`;
    writeFileSync(join(outDir, `${file}${suffix}.png`), png);
  }
}

function camel(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, letter: string) =>
    letter.toUpperCase(),
  );
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const entries: string[] = [];
for (const name of TOOLBAR) {
  render(name, toSvg(readNode(name), 2), TOOLBAR_POINTS);
  entries.push(`  "${name}": require("../../assets/glyphs/${name}.png"),`);
}
const tabEntries: string[] = [];
for (const name of TABS) {
  const node = readNode(name);
  render(`tab-${name}`, toSvg(node, 2), TAB_POINTS);
  render(`tab-${name}-selected`, toSvg(node, 2.5), TAB_POINTS);
  tabEntries.push(
    `  ${camel(name)}: {\n    default: require("../../assets/glyphs/tab-${name}.png"),\n    selected: require("../../assets/glyphs/tab-${name}-selected.png"),\n  },`,
  );
}

writeFileSync(
  join(root, "src/ui/glyphs.ts"),
  `// Generated by scripts/render-glyphs.ts. Do not edit.
import type { ImageSourcePropType } from "react-native";

/**
 * Lucide icons as template PNGs for native chrome. Pass them with
 * \`iconRenderingMode="template"\` so the bar tints them.
 */
export const glyphs = {
${entries.join("\n")}
} satisfies Record<string, ImageSourcePropType>;

export type GlyphName = keyof typeof glyphs;

export const tabGlyphs = {
${tabEntries.join("\n")}
} satisfies Record<
  string,
  { default: ImageSourcePropType; selected: ImageSourcePropType }
>;
`,
);

console.log(
  `Rendered ${TOOLBAR.length} toolbar and ${TABS.length} tab glyphs to assets/glyphs`,
);
