// CommonJS on purpose: Expo compiles app.config.ts but requires plugins as
// plain JavaScript.
const fs = require("node:fs");
const path = require("node:path");
const {
  withDangerousMod,
  withEntitlementsPlist,
  withInfoPlist,
  withXcodeProject,
} = require("expo/config-plugins");

// Native targets and sources the Expo template has no notion of, added to the
// generated project from Swift kept beside the app: a WidgetKit extension
// (widgets, Live Activities, Control Center controls) and Swift compiled
// straight into the app target (App Intents, whose metadata Xcode only
// extracts from the app's own sources, never from a CocoaPods library).
//
// Generalised from apps/macros-mobile/plugins/with-widgets.js, which predates
// it. `ios/` is regenerated by every prebuild, so nothing here is idempotent
// across runs by design — it is idempotent within one.

const FILE_TYPES = {
  ".swift": "sourcecode.swift",
  ".plist": "text.plist.xml",
  ".entitlements": "text.plist.entitlements",
};

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

/** A property list from plain JSON: strings, booleans, numbers, arrays, dicts. */
function plist(entries) {
  const encode = (value, indent) => {
    if (Array.isArray(value)) {
      return `<array>\n${value.map((item) => `${indent}\t${encode(item, `${indent}\t`)}\n`).join("")}${indent}</array>`;
    }
    if (typeof value === "boolean") return value ? "<true/>" : "<false/>";
    if (typeof value === "number") {
      return Number.isInteger(value)
        ? `<integer>${value}</integer>`
        : `<real>${value}</real>`;
    }
    if (value && typeof value === "object") {
      const body = Object.entries(value)
        .map(
          ([key, item]) =>
            `${indent}\t<key>${escapeXml(key)}</key>\n${indent}\t${encode(item, `${indent}\t`)}\n`,
        )
        .join("");
      return `<dict>\n${body}${indent}</dict>`;
    }
    return `<string>${escapeXml(value)}</string>`;
  };
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
${encode(entries, "")}
</plist>
`;
}

/**
 * Every `.swift` file in `dirs` (relative to the project root), by the name
 * it will have in the generated group. Two files of one name would overwrite
 * each other there, so that is refused.
 */
function swiftSources(projectRoot, dirs) {
  const files = new Map();
  for (const dir of dirs) {
    const absolute = path.join(projectRoot, dir);
    for (const name of fs.readdirSync(absolute).sort()) {
      if (!name.endsWith(".swift")) continue;
      if (files.has(name)) {
        throw new Error(
          `expo-ios-targets: ${name} is in both ${files.get(name)} and ${dir}`,
        );
      }
      files.set(name, dir);
    }
  }
  return [...files.entries()].map(([name, dir]) => ({
    name,
    source: path.join(projectRoot, dir, name),
  }));
}

function objectsOf(project) {
  return project.hash.project.objects;
}

function adder(project) {
  const objects = objectsOf(project);
  return (section, uuid, object, comment) => {
    objects[section] ??= {};
    objects[section][uuid] = object;
    objects[section][`${uuid}_comment`] = comment;
  };
}

/** File references in a new group under the main group; returns their ids. */
function addGroup(project, groupPath, names) {
  const add = adder(project);
  const references = names.map((name) => {
    const uuid = project.generateUuid();
    add(
      "PBXFileReference",
      uuid,
      {
        isa: "PBXFileReference",
        lastKnownFileType: FILE_TYPES[path.extname(name)],
        path: `"${name}"`,
        sourceTree: '"<group>"',
      },
      name,
    );
    return { name, uuid };
  });
  const groupId = project.generateUuid();
  add(
    "PBXGroup",
    groupId,
    {
      isa: "PBXGroup",
      children: references.map(({ name, uuid }) => ({
        value: uuid,
        comment: name,
      })),
      path: `"${groupPath}"`,
      sourceTree: '"<group>"',
    },
    groupPath,
  );
  const mainGroupId = project.getFirstProject().firstProject.mainGroup;
  project
    .getPBXGroupByKey(mainGroupId)
    .children.push({ value: groupId, comment: groupPath });
  return references;
}

function buildFiles(project, references) {
  const add = adder(project);
  return references
    .filter(({ name }) => name.endsWith(".swift"))
    .map(({ name, uuid }) => {
      const buildFile = project.generateUuid();
      add(
        "PBXBuildFile",
        buildFile,
        { isa: "PBXBuildFile", fileRef: uuid, fileRef_comment: name },
        `${name} in Sources`,
      );
      return { value: buildFile, comment: `${name} in Sources` };
    });
}

function applicationTarget(project) {
  const targets = project.pbxNativeTargetSection();
  for (const [uuid, target] of Object.entries(targets)) {
    if (typeof target !== "object") continue;
    if (target.productType === '"com.apple.product-type.application"') {
      return { uuid, target };
    }
  }
  throw new Error("expo-ios-targets: the project has no application target");
}

/**
 * @param {import("expo/config-plugins").ExpoConfig} config
 * @param {{
 *   name: string,
 *   bundleSuffix: string,
 *   displayName: string,
 *   sources: string[],
 *   deploymentTarget: string,
 *   entitlements?: Record<string, unknown>,
 *   infoPlist?: Record<string, unknown>,
 *   swiftConditions?: string[],
 * }} options
 */
function withExtensionTarget(config, options) {
  const bundleIdentifier = config.ios?.bundleIdentifier;
  if (!bundleIdentifier) {
    throw new Error("expo-ios-targets: ios.bundleIdentifier is required.");
  }
  const target = options.name;
  const extensionBundleId = `${bundleIdentifier}.${options.bundleSuffix}`;

  config = withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    if (project.pbxTargetByName(target)) return mod;
    const objects = objectsOf(project);
    // `addTarget` wires the dependency through these and skips it silently
    // when they are missing, which a single-target template project is.
    objects.PBXTargetDependency ??= {};
    objects.PBXContainerItemProxy ??= {};

    const created = project.addTarget(
      target,
      "app_extension",
      target,
      extensionBundleId,
    );
    const sources = swiftSources(mod.modRequest.projectRoot, options.sources);
    const references = addGroup(project, target, [
      ...sources.map(({ name }) => name),
      "Info.plist",
      `${target}.entitlements`,
    ]);
    const add = adder(project);
    const phases = [
      ["PBXSourcesBuildPhase", "Sources", buildFiles(project, references)],
      ["PBXFrameworksBuildPhase", "Frameworks", []],
      ["PBXResourcesBuildPhase", "Resources", []],
    ].map(([isa, comment, files]) => {
      const uuid = project.generateUuid();
      add(
        isa,
        uuid,
        {
          isa,
          buildActionMask: 2147483647,
          files,
          runOnlyForDeploymentPostprocessing: 0,
        },
        comment,
      );
      return { value: uuid, comment };
    });
    created.pbxNativeTarget.buildPhases.push(...phases);

    // The embed phase `addTarget` creates is called "Copy Files"; Xcode's own
    // name says what it is for.
    const copyPhases = objects.PBXCopyFilesBuildPhase ?? {};
    for (const [key, phase] of Object.entries(copyPhases)) {
      if (typeof phase !== "object" || phase.name !== '"Copy Files"') continue;
      phase.name = '"Embed Foundation Extensions"';
      copyPhases[`${key}_comment`] = "Embed Foundation Extensions";
    }

    const team = config.ios?.appleTeamId;
    const list =
      objects.XCConfigurationList[
        created.pbxNativeTarget.buildConfigurationList
      ];
    for (const { value } of list.buildConfigurations) {
      const configuration = objects.XCBuildConfiguration[value];
      const debug = configuration.name === "Debug";
      const conditions = [
        "$(inherited)",
        ...(debug ? ["DEBUG"] : []),
        ...(options.swiftConditions ?? []),
      ];
      configuration.buildSettings = {
        APPLICATION_EXTENSION_API_ONLY: "YES",
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: '""',
        CLANG_ENABLE_MODULES: "YES",
        CODE_SIGN_ENTITLEMENTS: `${target}/${target}.entitlements`,
        CODE_SIGN_STYLE: "Automatic",
        CURRENT_PROJECT_VERSION: `"${config.ios?.buildNumber ?? "1"}"`,
        ...(team ? { DEVELOPMENT_TEAM: team } : {}),
        ...(debug ? { DEBUG_INFORMATION_FORMAT: "dwarf" } : {}),
        GENERATE_INFOPLIST_FILE: "NO",
        INFOPLIST_FILE: `${target}/Info.plist`,
        IPHONEOS_DEPLOYMENT_TARGET: options.deploymentTarget,
        LD_RUNPATH_SEARCH_PATHS:
          '"$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"',
        MARKETING_VERSION: `"${config.version ?? "1.0.0"}"`,
        PRODUCT_BUNDLE_IDENTIFIER: `"${extensionBundleId}"`,
        PRODUCT_NAME: '"$(TARGET_NAME)"',
        SKIP_INSTALL: "YES",
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: `"${conditions.join(" ")}"`,
        SWIFT_EMIT_LOC_STRINGS: "YES",
        ...(debug ? { SWIFT_OPTIMIZATION_LEVEL: '"-Onone"' } : {}),
        SWIFT_VERSION: "5.0",
        TARGETED_DEVICE_FAMILY: '"1"',
      };
    }
    return mod;
  });

  config = withDangerousMod(config, [
    "ios",
    (mod) => {
      const { projectRoot, platformProjectRoot } = mod.modRequest;
      const destination = path.join(platformProjectRoot, target);
      fs.rmSync(destination, { recursive: true, force: true });
      fs.mkdirSync(destination, { recursive: true });
      for (const { name, source } of swiftSources(
        projectRoot,
        options.sources,
      )) {
        fs.copyFileSync(source, path.join(destination, name));
      }
      fs.writeFileSync(
        path.join(destination, "Info.plist"),
        plist({
          CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)",
          CFBundleDisplayName: options.displayName,
          CFBundleExecutable: "$(EXECUTABLE_NAME)",
          CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)",
          CFBundleInfoDictionaryVersion: "6.0",
          CFBundleName: "$(PRODUCT_NAME)",
          CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)",
          CFBundleShortVersionString: "$(MARKETING_VERSION)",
          CFBundleVersion: "$(CURRENT_PROJECT_VERSION)",
          NSExtension: {
            NSExtensionPointIdentifier: "com.apple.widgetkit-extension",
          },
          ...options.infoPlist,
        }),
      );
      fs.writeFileSync(
        path.join(destination, `${target}.entitlements`),
        plist(options.entitlements ?? {}),
      );
      return mod;
    },
  ]);
  return config;
}

/**
 * Swift compiled into the app target itself, from `sources` (directories
 * relative to the project root), copied into `ios/<group>/`.
 *
 * @param {import("expo/config-plugins").ExpoConfig} config
 * @param {{ group: string, sources: string[] }} options
 */
function withAppSources(config, options) {
  config = withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    const sources = swiftSources(mod.modRequest.projectRoot, options.sources);
    const references = addGroup(
      project,
      options.group,
      sources.map(({ name }) => name),
    );
    const { target } = applicationTarget(project);
    const phases = project.hash.project.objects.PBXSourcesBuildPhase;
    const phaseRef = target.buildPhases.find(({ value }) => value in phases);
    if (!phaseRef) {
      throw new Error("expo-ios-targets: the app target has no Sources phase");
    }
    phases[phaseRef.value].files.push(...buildFiles(project, references));
    return mod;
  });
  return withDangerousMod(config, [
    "ios",
    (mod) => {
      const { projectRoot, platformProjectRoot } = mod.modRequest;
      const destination = path.join(platformProjectRoot, options.group);
      fs.rmSync(destination, { recursive: true, force: true });
      fs.mkdirSync(destination, { recursive: true });
      for (const { name, source } of swiftSources(
        projectRoot,
        options.sources,
      )) {
        fs.copyFileSync(source, path.join(destination, name));
      }
      return mod;
    },
  ]);
}

/**
 * Entitlements and Info.plist keys on the app itself.
 *
 * @param {import("expo/config-plugins").ExpoConfig} config
 * @param {{ entitlements?: Record<string, unknown>, infoPlist?: Record<string, unknown> }} options
 */
function withAppCapabilities(config, options) {
  config = withEntitlementsPlist(config, (mod) => {
    Object.assign(mod.modResults, options.entitlements ?? {});
    return mod;
  });
  return withInfoPlist(config, (mod) => {
    Object.assign(mod.modResults, options.infoPlist ?? {});
    return mod;
  });
}

/**
 * The template turns on ENABLE_USER_SCRIPT_SANDBOXING while the "Bundle React
 * Native code and images" phase declares no outputs, so a Release build that
 * finds a main.jsbundle already in the products directory dies on
 * `deny file-write-unlink` (see Macros' without-script-sandboxing.js).
 */
function withoutScriptSandboxing(config) {
  return withXcodeProject(config, (mod) => {
    const configurations = mod.modResults.pbxXCBuildConfigurationSection();
    for (const entry of Object.values(configurations)) {
      if (typeof entry !== "object" || !entry.buildSettings) continue;
      entry.buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = "NO";
    }
    return mod;
  });
}

const withSceneLifecycle = require("./scene-lifecycle");

module.exports = {
  plist,
  withSceneLifecycle,
  swiftSources,
  withAppCapabilities,
  withAppSources,
  withExtensionTarget,
  withoutScriptSandboxing,
};
