[DEFAULT]
banaction = ufw
ignoreip = 127.0.0.1/8 ::1 100.64.0.0/10 192.168.1.0/24
bantime = 1h
findtime = 10m
maxretry = 6

[sshd]
enabled = true
backend = systemd
port = 22
maxretry = 5

[deniz-cloud-postgres]
enabled = true
backend = systemd
filter = deniz-cloud-postgres
port = 5433

[deniz-cloud-mongodb]
enabled = true
backend = systemd
filter = deniz-cloud-mongodb
port = 27018

[deniz-cloud-redis]
enabled = true
backend = systemd
filter = deniz-cloud-redis
port = 6380,6381
