// Generated by scripts/render-glyphs.ts. Do not edit.
import type { ImageSourcePropType } from "react-native";

/**
 * Lucide icons as template PNGs for native chrome. Pass them with
 * `iconRenderingMode="template"` so the bar tints them.
 */
export const glyphs = {
  "arrow-up-down": require("../../assets/glyphs/arrow-up-down.png"),
  braces: require("../../assets/glyphs/braces.png"),
  calendar: require("../../assets/glyphs/calendar.png"),
  "chart-column": require("../../assets/glyphs/chart-column.png"),
  check: require("../../assets/glyphs/check.png"),
  "circle-check": require("../../assets/glyphs/circle-check.png"),
  "circle-ellipsis": require("../../assets/glyphs/circle-ellipsis.png"),
  "circle-user": require("../../assets/glyphs/circle-user.png"),
  copy: require("../../assets/glyphs/copy.png"),
  ellipsis: require("../../assets/glyphs/ellipsis.png"),
  flame: require("../../assets/glyphs/flame.png"),
  "list-plus": require("../../assets/glyphs/list-plus.png"),
  "list-x": require("../../assets/glyphs/list-x.png"),
  "log-out": require("../../assets/glyphs/log-out.png"),
  "notebook-pen": require("../../assets/glyphs/notebook-pen.png"),
  pencil: require("../../assets/glyphs/pencil.png"),
  plus: require("../../assets/glyphs/plus.png"),
  "scan-barcode": require("../../assets/glyphs/scan-barcode.png"),
  "scan-text": require("../../assets/glyphs/scan-text.png"),
  share: require("../../assets/glyphs/share.png"),
  "shopping-cart": require("../../assets/glyphs/shopping-cart.png"),
  "square-pen": require("../../assets/glyphs/square-pen.png"),
  "table-2": require("../../assets/glyphs/table-2.png"),
  trash: require("../../assets/glyphs/trash.png"),
  "triangle-alert": require("../../assets/glyphs/triangle-alert.png"),
  utensils: require("../../assets/glyphs/utensils.png"),
  x: require("../../assets/glyphs/x.png"),
} satisfies Record<string, ImageSourcePropType>;

export type GlyphName = keyof typeof glyphs;

export const tabGlyphs = {
  layoutTemplate: {
    default: require("../../assets/glyphs/tab-layout-template.png"),
    selected: require("../../assets/glyphs/tab-layout-template-selected.png"),
  },
  apple: {
    default: require("../../assets/glyphs/tab-apple.png"),
    selected: require("../../assets/glyphs/tab-apple-selected.png"),
  },
  circlePlus: {
    default: require("../../assets/glyphs/tab-circle-plus.png"),
    selected: require("../../assets/glyphs/tab-circle-plus-selected.png"),
  },
  chartLine: {
    default: require("../../assets/glyphs/tab-chart-line.png"),
    selected: require("../../assets/glyphs/tab-chart-line-selected.png"),
  },
  circleEllipsis: {
    default: require("../../assets/glyphs/tab-circle-ellipsis.png"),
    selected: require("../../assets/glyphs/tab-circle-ellipsis-selected.png"),
  },
} satisfies Record<
  string,
  { default: ImageSourcePropType; selected: ImageSourcePropType }
>;
